services:
  - type: web
    name: servicenow-backend
    env: node
    buildCommand: npm install && npm rebuild bcrypt --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
